# Generated by Django 5.1.4 on 2025-01-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='reference_number',
            field=models.CharField(default='TvsGtF8ta9C8IdmnWCvr', max_length=50),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='reference_number',
            field=models.CharField(default='9R8xrOG1uf3Z0kWIw00F', max_length=50),
        ),
    ]
