# Generated by Django 5.1.4 on 2025-01-07 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='reference_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='reference_number',
            field=models.CharField(default='SDVyoor1WHlwuOtj6uBQ', max_length=50),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='reference_number',
            field=models.CharField(default='7NWI0ngz14RD3swnBiRv', max_length=50),
        ),
    ]
