# Generated by Django 5.1.4 on 2025-01-08 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_transactionhistory_reference_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('account', models.CharField(max_length=100)),
                ('account_name', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='deposit',
            name='reference_number',
            field=models.CharField(default='hEZ4VTNVWI68WGGpDxH9', max_length=50),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='reference_number',
            field=models.CharField(default='23oQLJYL8RYNAJyWduxE', max_length=50),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payments.paymentmethod'),
        ),
    ]
