# Generated by Django 5.1.4 on 2025-01-09 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_paymentmethod_alter_deposit_reference_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionhistory',
            options={'verbose_name_plural': 'Transaction Histories'},
        ),
        migrations.AlterField(
            model_name='deposit',
            name='reference_number',
            field=models.CharField(default='ELdDkIhxwxyo3qAPWAaq', max_length=50),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='reference_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='reference_number',
            field=models.CharField(default='MuHKaXcELWvna5DLAS8T', max_length=50),
        ),
    ]
