# Generated by Django 5.1.4 on 2025-01-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_transactionhistory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='reference_number',
            field=models.CharField(default='zfBhBm5MESYes7XKsikj', max_length=50),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='reference_number',
            field=models.CharField(default='nHi9eXChEYTgPJd4Fba3', max_length=50),
        ),
    ]
