# Generated by Django 5.1.4 on 2025-02-01 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_deposit_reference_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='reference_number',
            field=models.CharField(default='HPUSDAtHBeqYFoGsRUrD', max_length=50),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='reference_number',
            field=models.CharField(default='vNv5vu0Ic4rXmrzusDmx', max_length=50),
        ),
    ]
