# Generated by Django 5.1.4 on 2025-01-22 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_deposit_reference_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='reference_number',
            field=models.CharField(default='LAa4cBaTxRyVNMK7MAT9', max_length=50),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='reference_number',
            field=models.CharField(default='QS7P528N76v2ZAGcv6cI', max_length=50),
        ),
    ]
