# Generated by Django 5.1.4 on 2025-01-22 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minislot',
            name='amount',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='minislot',
            name='stake',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
    ]
