# Generated by Django 5.1.4 on 2025-01-23 00:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_minislot_amount_alter_minislot_stake'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BottleSpin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stake', models.IntegerField(blank=True, max_length=50, null=True)),
                ('amount', models.IntegerField(blank=True, max_length=50, null=True)),
                ('option', models.CharField(blank=True, choices=[('UP', 'UP'), ('DOWN', 'DOWN')], max_length=50, null=True)),
                ('outcome', models.CharField(blank=True, choices=[('UP', 'UP'), ('DOWN', 'DOWN')], max_length=50, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('LOSS', 'LOSS'), ('WON', 'WON')], default='PENDING', max_length=50)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HeadorTail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stake', models.IntegerField(blank=True, max_length=50, null=True)),
                ('amount', models.IntegerField(blank=True, max_length=50, null=True)),
                ('option', models.CharField(blank=True, choices=[('HEAD', 'HEAD'), ('TAIL', 'TAIL')], max_length=50, null=True)),
                ('outcome', models.CharField(blank=True, choices=[('HEAD', 'HEAD'), ('TAIL', 'TAIL')], max_length=50, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('LOSS', 'LOSS'), ('WON', 'WON')], default='PENDING', max_length=50)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RockPapperSissors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stake', models.IntegerField(blank=True, max_length=50, null=True)),
                ('amount', models.IntegerField(blank=True, max_length=50, null=True)),
                ('option', models.CharField(blank=True, choices=[('ROCK', 'ROCK'), ('PAPER', 'PAPER'), ('SISSORS', 'SISSORS')], max_length=50, null=True)),
                ('outcome', models.CharField(blank=True, choices=[('ROCK', 'ROCK'), ('PAPER', 'PAPER'), ('SISSORS', 'SISSORS')], max_length=50, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('LOSS', 'LOSS'), ('WON', 'WON'), ('DRAW', 'DRAW')], default='PENDING', max_length=50)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
